site_name: OpenShift as a Service
docs_dir: content
site_url: https://docs.stakater.com/oaas/
repo_url: https://github.com/stakater/oaas-docs
edit_uri: blob/main/content/
use_directory_urls: false
theme:
  name: material
  logo: assets/images/favicon.svg
  favicon: assets/images/favicon.svg
  custom_dir: dist/_theme
  palette:
    primary: white
  features:
    - content.code.copy
    - content.code.select

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - OpenShift as a Service:
      - index.md
      - general-provisions.md
      - service-composition.md
      - business-hours.md
      - technical-support.md
      - updating-clusters.md
      - Runbooks:
          - upgrades.md
      - sla.md
      - cost.md
  - Stakater Home: https://www.stakater.com/
  - SAAP: https://www.stakater.com/saap-kubernetes-openshift
  - Consultancy: https://www.stakater.com/kubernetes-consultancy
  - Events: https://www.stakater.com/events
  - Platform Assessment: https://www.stakater.com/kubernetes-platform-assessment
  - Careers: https://www.stakater.com/careers
plugins:
  - search
