site_name: KubeCare+
docs_dir: content
site_url: https://docs.stakater.com/kubecareplus/
repo_url: https://github.com/stakater/kubecareplus-docs
edit_uri: blob/main/content/
use_directory_urls: false

theme:
  logo: assets/images/favicon.svg
  favicon: assets/images/favicon.svg
  features:
    - content.code.copy
    - content.code.select

nav:
  - KubeCare+:
      - index.md
      - general-provisions.md
      - service-composition.md
      - business-hours.md
      - technical-support.md
      - updating-clusters.md
      - Runbooks:
          - upgrades.md
      - sla.md
      - cost.md
