name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
<<<<<<< Updated upstream
    uses: stakater/.github/.github/workflows/release_template.yaml@v0.0.43
=======
    uses: stakater/.github/.github/workflows/release_template.yaml@v0.0.64
>>>>>>> Stashed changes
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
